## shuffle

 

```
Original array  
a = np.array([[10, 11, 12], [20, 21, 22], [30, 31, 32],[40, 41, 42]])  
print(a)  
[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]]
Keep row order, shuffle colums within each row  
print(np.apply_along_axis(np.random.permutation, 1, a))  
[[11 12 10]
 [22 21 20]
 [31 30 32]
 [40 41 42]]
Keep colums order, shuffle rows within each column  
print(np.apply_along_axis(np.random.permutation, 0, a))  
[[40 41 32]
 [20 31 42]
 [10 11 12]
 [30 21 22]]
Original array is unchanged  
print(a)  
[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]]

 ```

In [ ]:

def shuffle(df, n=1, axis=0):     
    df = df.copy()
    for _ in range(n):
        df.apply(np.random.shuffle, axis=axis)
    return df

# For DF
df = df.sample(frac=1, axis=1).reset_index(drop=True)

# For Series
s.sample() # return one row
s.sample(n=3) # return 3 row
s.sample(frac=0.5)
import sklearn.utils
df = sklearn.utils.shuffle(df)

import numpy as np
df = df.apply(np.random.permutation, axis=1)  